/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.visao.outros.corporativo;

import com.mycompany.ferramentas.BancoDeDadosMySql;
import com.mycompany.ferramentas.Formularios;
import com.mycompany.visao.categoria.CadCategoria;
import com.mycompany.visao.categoria.ListCategoria;
import com.mycompany.visao.cidade.CadCidade;
import com.mycompany.visao.cidade.ListCidade;
import com.mycompany.visao.endereco.CadEndereco;
import com.mycompany.visao.endereco.ListEndereco;
import com.mycompany.visao.estado.CadEstado;
import com.mycompany.visao.estado.ListEstado;
import com.mycompany.visao.estadocivil.CadEstadoCivil;
import com.mycompany.visao.estadocivil.ListEstadoCivil;
import com.mycompany.visao.marca.CadMarca;
import com.mycompany.visao.marca.ListMarca;
import com.mycompany.visao.pais.CadPais;
import com.mycompany.visao.pais.ListPais;
import com.mycompany.visao.produto.CadProduto;
import com.mycompany.visao.produto.ListProduto;
import javax.swing.JOptionPane;

/**
 *
 * @author arthur.7923
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
        setLocationRelativeTo(null);
        
        setExtendedState(MAXIMIZED_BOTH);
        
        if (!BancoDeDadosMySql.conectar()) {
            JOptionPane.showMessageDialog( null, "Não foi possivel conectar ao banco de dados. O sistema será finalizado.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        menuBar1 = new javax.swing.JMenu();
        miCadastroCategoria = new javax.swing.JMenuItem();
        miCadastroMarca = new javax.swing.JMenuItem();
        miCadastroPais = new javax.swing.JMenuItem();
        miCadastroEstado = new javax.swing.JMenuItem();
        miCadastroCidade = new javax.swing.JMenuItem();
        miCadastroProduto = new javax.swing.JMenuItem();
        miCadastroEstado_Civil = new javax.swing.JMenuItem();
        miCadastroEndereco = new javax.swing.JMenuItem();
        menuBar2 = new javax.swing.JMenu();
        miConsultaCategoria = new javax.swing.JMenuItem();
        miConsultaMarca = new javax.swing.JMenuItem();
        miConsultaPais = new javax.swing.JMenuItem();
        miConsultaEstado = new javax.swing.JMenuItem();
        miConsultaCidade = new javax.swing.JMenuItem();
        miConsultaProduto = new javax.swing.JMenuItem();
        miConsultaEstado_Civil = new javax.swing.JMenuItem();
        miConsultaEndereco = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 291, Short.MAX_VALUE)
        );

        menuBar1.setText("Cadastros");
        menuBar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBar1ActionPerformed(evt);
            }
        });

        miCadastroCategoria.setText("Categoria");
        miCadastroCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCategoriaActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroCategoria);

        miCadastroMarca.setText("Marca");
        miCadastroMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroMarcaActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroMarca);

        miCadastroPais.setText("País");
        miCadastroPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroPaisActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroPais);

        miCadastroEstado.setText("Estado");
        miCadastroEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEstadoActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroEstado);

        miCadastroCidade.setText("Cidade");
        miCadastroCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroCidadeActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroCidade);

        miCadastroProduto.setText("Produto");
        miCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroProdutoActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroProduto);

        miCadastroEstado_Civil.setText("Estado_Civil");
        miCadastroEstado_Civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEstado_CivilActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroEstado_Civil);

        miCadastroEndereco.setText("Endereco");
        miCadastroEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCadastroEnderecoActionPerformed(evt);
            }
        });
        menuBar1.add(miCadastroEndereco);

        menuBar.add(menuBar1);
        menuBar1.getAccessibleContext().setAccessibleDescription("");

        menuBar2.setText("Consultas");

        miConsultaCategoria.setText("Categoria");
        miConsultaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCategoriaActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaCategoria);

        miConsultaMarca.setText("Marca");
        miConsultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaMarcaActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaMarca);

        miConsultaPais.setText("País");
        miConsultaPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaPaisActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaPais);

        miConsultaEstado.setText("Estado");
        miConsultaEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEstadoActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaEstado);

        miConsultaCidade.setText("Cidade");
        miConsultaCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaCidadeActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaCidade);

        miConsultaProduto.setText("Produto");
        miConsultaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaProdutoActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaProduto);

        miConsultaEstado_Civil.setText("Estado_Civil");
        miConsultaEstado_Civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEstado_CivilActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaEstado_Civil);

        miConsultaEndereco.setText("Endereco");
        miConsultaEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miConsultaEnderecoActionPerformed(evt);
            }
        });
        menuBar2.add(miConsultaEndereco);

        menuBar.add(menuBar2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCadastroCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCategoriaActionPerformed
        //CadCategoria cadCategoria = new CadCategoria();
        if(Formularios.cadCategoria == null)
            Formularios.cadCategoria = new CadCategoria();
        
        Formularios.cadCategoria.setVisible(true);
    }//GEN-LAST:event_miCadastroCategoriaActionPerformed

    private void miConsultaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCategoriaActionPerformed
        //ListCategoria listCategoria = new ListCategoria();
        Formularios.listCategoria = new ListCategoria();
        Formularios.listCategoria.setVisible(true);
    }//GEN-LAST:event_miConsultaCategoriaActionPerformed

    private void menuBar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuBar1ActionPerformed

    private void miCadastroMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroMarcaActionPerformed
       if(Formularios.cadMarca == null)
            Formularios.cadMarca = new CadMarca();
       
        Formularios.cadMarca.setVisible(true);
    }//GEN-LAST:event_miCadastroMarcaActionPerformed

    private void miConsultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaMarcaActionPerformed
                Formularios.listMarca = new ListMarca();
        Formularios.listMarca.setVisible(true);
    }//GEN-LAST:event_miConsultaMarcaActionPerformed

    private void miCadastroEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEstadoActionPerformed
        if(Formularios.cadEstado == null)
            Formularios.cadEstado = new CadEstado();
         
         Formularios.cadEstado.setVisible(true);
    }//GEN-LAST:event_miCadastroEstadoActionPerformed

    private void miCadastroPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroPaisActionPerformed
         if(Formularios.cadPais == null)
            Formularios.cadPais = new CadPais();
         
         Formularios.cadPais.setVisible(true);
    }//GEN-LAST:event_miCadastroPaisActionPerformed

    private void miConsultaEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEstadoActionPerformed
        Formularios.listEstado = new ListEstado();
        Formularios.listEstado.setVisible(true);
    }//GEN-LAST:event_miConsultaEstadoActionPerformed

    private void miCadastroCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroCidadeActionPerformed
        if(Formularios.cadCidade == null)
            Formularios.cadCidade = new CadCidade();
       
        Formularios.cadCidade.setVisible(true);
    }//GEN-LAST:event_miCadastroCidadeActionPerformed

    private void miConsultaPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaPaisActionPerformed
         Formularios.listPais = new ListPais();
        Formularios.listPais.setVisible(true);
    }//GEN-LAST:event_miConsultaPaisActionPerformed

    private void miConsultaCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaCidadeActionPerformed
        Formularios.listCidade = new ListCidade();
        Formularios.listCidade.setVisible(true);
    }//GEN-LAST:event_miConsultaCidadeActionPerformed

    private void miCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroProdutoActionPerformed
        if(Formularios.cadProduto == null)
            Formularios.cadProduto = new CadProduto();
       
        Formularios.cadProduto.setVisible(true);
    }//GEN-LAST:event_miCadastroProdutoActionPerformed

    private void miConsultaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaProdutoActionPerformed
        Formularios.listProduto = new ListProduto();
        Formularios.listProduto.setVisible(true);
    }//GEN-LAST:event_miConsultaProdutoActionPerformed

    private void miCadastroEstado_CivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEstado_CivilActionPerformed
        if(Formularios.cadEstadoCivil == null)
            Formularios.cadEstadoCivil = new CadEstadoCivil();
       
        Formularios.cadEstadoCivil.setVisible(true);
    }//GEN-LAST:event_miCadastroEstado_CivilActionPerformed

    private void miConsultaEstado_CivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEstado_CivilActionPerformed
        Formularios.listEstadoCivil = new ListEstadoCivil();
        Formularios.listEstadoCivil.setVisible(true);
    }//GEN-LAST:event_miConsultaEstado_CivilActionPerformed

    private void miCadastroEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCadastroEnderecoActionPerformed
        if(Formularios.cadEndereco == null)
            Formularios.cadEndereco = new CadEndereco();
        
        Formularios.cadEndereco.setVisible(true);
    }//GEN-LAST:event_miCadastroEnderecoActionPerformed

    private void miConsultaEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miConsultaEnderecoActionPerformed
        Formularios.listEndereco = new ListEndereco();
        Formularios.listEndereco.setVisible(true);
    }//GEN-LAST:event_miConsultaEnderecoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBar1;
    private javax.swing.JMenu menuBar2;
    private javax.swing.JMenuItem miCadastroCategoria;
    private javax.swing.JMenuItem miCadastroCidade;
    private javax.swing.JMenuItem miCadastroEndereco;
    private javax.swing.JMenuItem miCadastroEstado;
    private javax.swing.JMenuItem miCadastroEstado_Civil;
    private javax.swing.JMenuItem miCadastroMarca;
    private javax.swing.JMenuItem miCadastroPais;
    private javax.swing.JMenuItem miCadastroProduto;
    private javax.swing.JMenuItem miConsultaCategoria;
    private javax.swing.JMenuItem miConsultaCidade;
    private javax.swing.JMenuItem miConsultaEndereco;
    private javax.swing.JMenuItem miConsultaEstado;
    private javax.swing.JMenuItem miConsultaEstado_Civil;
    private javax.swing.JMenuItem miConsultaMarca;
    private javax.swing.JMenuItem miConsultaPais;
    private javax.swing.JMenuItem miConsultaProduto;
    // End of variables declaration//GEN-END:variables
}
